{{- if .Values.backend.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  name: {{ include "backend.fullname" . }}
annotations:
  haproxy.router.openshift.io/ip_whitelist: {{ .Values.ipWhitelist}}
spec:
  host: {{ include "backend.fullname" . }}.{{ .Values.global.domain }}
  port:
    targetPort: 5000
  to:
    kind: Service
    name: {{ include "backend.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}